### ISSUE TITLE
bugzilla plugin not counting assigned (and possibly other as well) bugs correctly

### ISSUE THREAD

**Issue by jhutar** [atodorov/qe-metrics#4]
Say I want to get bugs moved to ASSIGNED by mkorbel@redhat.com sometime from 2014-12-22 00:00:00 to 2014-12-28 23:59:59. So I run:

./qe-metrics --start 2014-12-22 --end 2014-12-28 --author mkorbel@redhat.com

One of found bugs is:

https://bugzilla.redhat.com/show_bug.cgi?id=801965

And this what plugin does:

    qd = {
        'query_format' : 'advanced',

        'field0-0-0' : 'bug_status',
        'type0-0-0' : 'changedto',
        'value0-0-0' : 'ASSIGNED',

        'field0-1-0' : 'bug_status',
        'type0-1-0' : 'changedby',
        'value0-1-0' : author,

        'field0-2-0' : 'bug_status',
        'type0-2-0' : 'changedafter',
        'value0-2-0' : start,

        'field0-3-0' : 'bug_status',
        'type0-3-0' : 'changedbefore',
        'value0-3-0' : end,
    }

    bugs = bz.query(qd)

So although bug was not modified between these timestamps, it was found as it was changed both after first timestamp (but later than second timestamp) and before second timestamp. Not talking about actual change to ASSIGNED which was done in a different time as well.

I do not know if there is some way out. What I assume is needed is to get history for each bug and search there.

**Comment by atodorov** [comment]
Hi Jan,
I suspect that either the query dictionary isn't what Bugzilla expects or it parses it differently. 

I've run the query by hand in bugzilla.redhat.com and I can see that query string parameters are named differently (maybe due to Bugzilla upgrade) compared to the names used in the script. 

https://bugzilla.redhat.com/buglist.cgi?f1=bug_status&f2=bug_status&f3=bug_status&f4=bug_status&list_id=3123846&o1=changedto&o2=changedafter&o3=changedbefore&o4=changedby&product=Red%20Hat%20Enterprise%20Linux%205&query_format=advanced&v1=ASSIGNED&v2=2014-12-22%2000%3A00%3A00&v3=2014-12-28%2023%3A59%3A59&v4=mkorbel%40redhat.com

Try using the new field names in the query dictionary above and see if there's any change.
I guess all of the Bugzilla queries need to be updated to match the new fields then.

**Comment by jhutar** [comment]
I have tried your query and noticed "&product=Red Hat Enterprise Linux 5" there. When I remove it, I'm back to result in comment 0 here (including bug 801965). So I guess that does not help.

**Comment by jhutar** [comment]
If you agree and do not see some obvious solution, I'll try to implement that history check, OK?

**Comment by atodorov** [comment]
I don't think you have to do this. I've found in Bugzilla webUI 3 separate options, related to how the fields are interpreted (under Custom search): 
* Match ALL of the following separately
* Match ANY of the following separately
* Match ALL of the following against the same field

The last one is what we need and it adds a `j_top=AND_G` to the query string but I'm unable to make use of it in Python yet. For some reason the Python query doesn't like this parameter.

**Comment by atodorov** [comment]
Hmmm, made it work with the new field names. Let me push a quick fix before I inspect all the other queries.
